### ISSUE TITLE
puck2.jar tourner parfois en boucle

### ISSUE THREAD

**Issue by mikalziane** [Skelly98/puck2#4]
On pense à tort que cela dépend uniquement du fait de le lancer depuis l'interface graphique .
En fait le puck2.jar version récente (avec des noms complets pour les méthodes et un champ violation) tourne en boucle si on se trompe de répertoire dans le menu graphique.
Il faut absolument "entrer dans le src".
Si on peut passe les arguments en ligne de commande il faut vérifier et documenter ici ce qu'on passer exactement et qui plante puck2.jar

**Comment by kellyseng** [comment]
puck2 ne tourne pas vraiment en boucle, le programme nous redonne la main pour que l'on puisse exécuter des commandes comme display ou prettyPrint lorsqu'on lui donne en argument le dossier du projet. Le manque d'indication (instructions) lors de l'exécution de puck2 nous a laissé pensé que le programme ne se termine pas.

J'ai ajouté un System.out.println(....) dans la méthode run pour un seul argument.
